// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("QuickGraph.Tests")]
[assembly: AssemblyProductAttribute("QuickGraph")]
[assembly: AssemblyDescriptionAttribute("Graph datastructures and algorithms for .NET.")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
