// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("QuickGraph.Perf")]
[assembly: AssemblyProductAttribute("QuickGraph")]
[assembly: AssemblyDescriptionAttribute("Graph datastructures and algorithms for .NET.")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
