// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("QuickGraph")]
[assembly: AssemblyProductAttribute("YC.QuickGraph")]
[assembly: AssemblyDescriptionAttribute("Graph datastructures and algorithms for .NET.")]
[assembly: AssemblyVersionAttribute("3.7.1")]
[assembly: AssemblyFileVersionAttribute("3.7.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.7.1";
        internal const string InformationalVersion = "3.7.1";
    }
}
