// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("QuickGraph")]
[assembly: AssemblyProductAttribute("QuickGraph")]
[assembly: AssemblyDescriptionAttribute("Graph datastructures and algorithms for .NET.")]
[assembly: AssemblyVersionAttribute("3.7.0")]
[assembly: AssemblyFileVersionAttribute("3.7.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.7.0";
        internal const string InformationalVersion = "3.7.0";
    }
}
