using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Algorithms
{
    
    
    public partial class DoubleDenseMatrixTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214056_0_01()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(0, 0, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214056_0_02()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214057_0_03()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(30, 0, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214100_0_04()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(29, 27, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214104_0_05()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 2, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214108_0_06()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(2, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214109_0_07()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 3, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214116_0_08()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 4, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214121_0_09()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(3, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214123_0_10()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 5, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214128_0_11()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 6, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214132_0_12()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(4, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214132_0_13()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 7, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214139_0_14()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 8, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214144_0_15()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 9, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214147_0_16()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(5, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214148_0_17()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 10, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214153_0_18()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 11, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214200_0_19()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 12, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214202_0_20()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(6, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214204_0_21()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 13, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214211_0_22()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 14, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214216_0_23()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 15, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214221_0_24()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(7, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214222_0_25()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 16, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
    }
}
