using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Algorithms
{
    
    
    public partial class DoubleDenseMatrixTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_230700_7_01()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(13, 2, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_231022_7_02()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(9, 3, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_231919_7_03()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(4, 7, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_232113_7_04()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(3, 9, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
    }
}
