using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Algorithms
{
    
    
    public partial class DoubleDenseMatrixTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214811_1_01()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 17, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214816_1_02()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 18, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214822_1_03()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 19, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214824_1_04()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(8, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214827_1_05()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 20, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214834_1_06()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 21, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214839_1_07()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 22, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214845_1_08()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 23, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214847_1_09()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(9, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214907_1_10()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(10, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_214919_1_11()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(29, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_215233_1_12()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(31, 0, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_215242_1_13()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(18, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_215311_1_14()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(32, 0, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_215318_1_15()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(19, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_215339_1_16()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(33, 0, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_215347_1_17()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(34, 0, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_215350_1_18()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(20, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_215425_1_19()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(35, 0, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_215427_1_20()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(21, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_215432_1_21()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(36, 0, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_215503_1_22()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(22, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_215505_1_23()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(37, 0, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_215515_1_24()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(38, 0, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.WriteMatrix(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteMatrix_DoubleDenseMatrix_70429_215544_1_25()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(23, 1, double.MinValue);
            this.WriteMatrix(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
    }
}
