using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Algorithms
{
    
    
    public partial class DoubleDenseMatrixTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_223801_5_01()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(0, 0, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxCalls+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_223801_5_02()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 1, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_223803_5_03()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(30, 0, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="QuickGraph.Algorithms.MatrixSizeMistmatchException">
        ///  Error in the application.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(QuickGraph.Algorithms.MatrixSizeMistmatchException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_223804_5_04()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(0, 27, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_223817_5_05()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(30, 27, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="QuickGraph.Algorithms.MatrixSizeMistmatchException">
        ///  Error in the application.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(QuickGraph.Algorithms.MatrixSizeMistmatchException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_223828_5_06()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 2, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="QuickGraph.Algorithms.MatrixSizeMistmatchException">
        ///  Error in the application.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(QuickGraph.Algorithms.MatrixSizeMistmatchException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_223832_5_07()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(2, 1, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="QuickGraph.Algorithms.MatrixSizeMistmatchException">
        ///  Error in the application.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(QuickGraph.Algorithms.MatrixSizeMistmatchException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_223845_5_08()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 3, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="QuickGraph.Algorithms.MatrixSizeMistmatchException">
        ///  Error in the application.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(QuickGraph.Algorithms.MatrixSizeMistmatchException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_223902_5_09()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 4, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="QuickGraph.Algorithms.MatrixSizeMistmatchException">
        ///  Error in the application.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(QuickGraph.Algorithms.MatrixSizeMistmatchException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_223913_5_10()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(3, 1, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="QuickGraph.Algorithms.MatrixSizeMistmatchException">
        ///  Error in the application.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(QuickGraph.Algorithms.MatrixSizeMistmatchException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_223920_5_11()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 5, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="QuickGraph.Algorithms.MatrixSizeMistmatchException">
        ///  Error in the application.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(QuickGraph.Algorithms.MatrixSizeMistmatchException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_223934_5_12()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 6, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="QuickGraph.Algorithms.MatrixSizeMistmatchException">
        ///  Error in the application.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(QuickGraph.Algorithms.MatrixSizeMistmatchException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_223943_5_13()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(4, 1, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="QuickGraph.Algorithms.MatrixSizeMistmatchException">
        ///  Error in the application.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(QuickGraph.Algorithms.MatrixSizeMistmatchException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_223953_5_14()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 7, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_224008_5_15()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 8, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxCalls+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_224009_5_16()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(2, 2, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_224028_5_17()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 9, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_224030_5_18()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(5, 1, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_224042_5_19()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 10, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_224056_5_20()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 11, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_224104_5_21()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(6, 1, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_224109_5_22()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 12, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_224123_5_23()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 13, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_224142_5_24()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(1, 14, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    Test did not terminate within configured Exploration Bounds. This failure may not reproduce without Pex.
        ///  </para>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=MaxConditions+exceeded for more information.
        ///  </para>
        ///</remarks>
        [QuickGraph.Unit.TestAttribute()]
        [QuickGraph.Unit.IgnoreAttribute("nontermination")]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.DoubleDenseMatrixTest), "DoubleDenseMatrixTest.SelfSimilarity(DoubleDenseMatrix)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SelfSimilarity_DoubleDenseMatrix_70429_224151_5_25()
        {
            QuickGraph.Algorithms.Matrix.DoubleDenseMatrix ddm0 = new QuickGraph.Algorithms.Matrix.DoubleDenseMatrix(7, 1, double.MinValue);
            this.SelfSimilarity(((QuickGraph.Algorithms.Matrix.DoubleDenseMatrix)(ddm0)));
        }
    }
}
