using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Algorithms
{
    
    
    public partial class SourceFirstTopologicalSortAlgorithmTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="System.ArgumentNullException">
        ///  Value cannot be null.
        ///Parameter name: visitedGraph
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(System.ArgumentNullException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.SourceFirstTopologicalSortAlgorithmTest), "SourceFirstTopologicalSortAlgorithmTest.Sort(IVertexAndEdgeListGraph<String,Edge<" +
            "String>>)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void Sort_IVertexAndEdgeListGraph2_70429_213350_1_01()
        {
            this.Sort(((QuickGraph.IVertexAndEdgeListGraph<string, QuickGraph.Edge<string>>)(null)));
        }
    }
}
