using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Algorithms
{
    
    
    public partial class StronglyConnectedComponentAlgorithmTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.StronglyConnectedComponentAlgorithmTest), "StronglyConnectedComponentAlgorithmTest.EmptyGraph()")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void EmptyGraph__70429_213528_0_01()
        {
            this.EmptyGraph();
        }
    }
}
