using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Algorithms
{
    
    
    public partial class TopologicalSortAlgorithmTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="QuickGraph.NonAcyclicGraphException">
        ///  Error in the application.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(QuickGraph.NonAcyclicGraphException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.TopologicalSortAlgorithmTest), "TopologicalSortAlgorithmTest.SortCyclic()")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void SortCyclic__70429_213354_0_01()
        {
            this.SortCyclic();
        }
    }
}
