using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Algorithms
{
    
    
    public partial class TopologicalSortAlgorithmTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.TopologicalSortAlgorithmTest), "TopologicalSortAlgorithmTest.SortCyclic(IVertexListGraph<String,Edge<String>>)")]
        [GeneratedCode("Pex", "1.1.20430.1")]
        public void SortCyclic_IVertexListGraph2_70502_012546_0_01()
        {
            QuickGraph.AdjacencyGraph<string, QuickGraph.Edge<string>> ag0 = new QuickGraph.AdjacencyGraph<string, QuickGraph.Edge<string>>(false);
            this.SortCyclic(((QuickGraph.IVertexListGraph<string, QuickGraph.Edge<string>>)(ag0)));
        }
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.TopologicalSortAlgorithmTest), "TopologicalSortAlgorithmTest.SortCyclic(IVertexListGraph<String,Edge<String>>)")]
        [GeneratedCode("Pex", "1.1.20430.1")]
        public void SortCyclic_IVertexListGraph2_70502_012547_0_02()
        {
            QuickGraph.AdjacencyGraph<string, QuickGraph.Edge<string>> ag0 = new QuickGraph.AdjacencyGraph<string, QuickGraph.Edge<string>>(false);
            QuickGraph.BidirectionalGraph<string, QuickGraph.Edge<string>> bg0 = new QuickGraph.BidirectionalGraph<string, QuickGraph.Edge<string>>(false);
            this.SortCyclic(((QuickGraph.IVertexListGraph<string, QuickGraph.Edge<string>>)(bg0)));
        }
    }
}
