using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Algorithms
{
    
    
    public partial class UndirectedTopologicalSortAlgorithmTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="System.ArgumentNullException">
        ///  Value cannot be null.
        ///Parameter name: visitedGraph
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(System.ArgumentNullException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.UndirectedTopologicalSortAlgorithmTest), "UndirectedTopologicalSortAlgorithmTest.Compute(IUndirectedGraph<String,Edge<Strin" +
            "g>>)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void Compute_IUndirectedGraph2_70429_213423_0_01()
        {
            this.Compute(((QuickGraph.IUndirectedGraph<string, QuickGraph.Edge<string>>)(null)));
        }
    }
}
