using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Algorithms
{
    
    
    public partial class WeaklyConnectedComponentsAlgorithmTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="System.NullReferenceException">
        ///  Object reference not set to an instance of an object.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(System.NullReferenceException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.WeaklyConnectedComponentsAlgorithmTest), "WeaklyConnectedComponentsAlgorithmTest.Compute(IVertexListGraph<String,Edge<Strin" +
            "g>>)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void Compute_IVertexListGraph2_70429_213505_0_01()
        {
            this.Compute(((QuickGraph.IVertexListGraph<string, QuickGraph.Edge<string>>)(null)));
        }
    }
}
