using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Serialization
{
    
    
    public partial class GraphMLSerializerTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Serialization.GraphMLSerializerTest), "GraphMLSerializerTest.RoundTrip()")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void RoundTrip__70429_213359_0_01()
        {
            this.RoundTrip();
        }
    }
}
