using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Serialization
{
    
    
    public partial class GraphMLSerializerWithArgumentsTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.Serialization.GraphMLSerializerWithArgumentsTest), "GraphMLSerializerWithArgumentsTest.WriteEdge()")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void WriteEdge__70429_213341_1_01()
        {
            this.WriteEdge();
        }
    }
}
