using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Serialization
{
    
    
    public partial class GraphMLSerializerTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="System.NullReferenceException">
        ///  Object reference not set to an instance of an object.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(System.NullReferenceException))]
        [PexGeneratedBy(typeof(QuickGraph.Serialization.GraphMLSerializerTest), "GraphMLSerializerTest.RoundTripGraph(IMutableVertexAndEdgeListGraph<NamedVertex,N" +
            "amedEdge>)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void RoundTripGraph_IMutableVertexAndEdgeListGraph2_70429_213403_1_01()
        {
            this.RoundTripGraph(((QuickGraph.IMutableVertexAndEdgeListGraph<QuickGraph.NamedVertex, QuickGraph.NamedEdge>)(null)));
        }
    }
}
