using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph
{
    
    
    public partial class FactoryCompilerTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.FactoryCompilerTest), "FactoryCompilerTest.CreateEdgeFactory()")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void CreateEdgeFactory__70429_213453_2_01()
        {
            this.CreateEdgeFactory();
        }
    }
}
