using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph
{
    
    
    public partial class UndirectedGraphTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="System.NullReferenceException">
        ///  Object reference not set to an instance of an object.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(System.NullReferenceException))]
        [PexGeneratedBy(typeof(QuickGraph.UndirectedGraphTest), "UndirectedGraphTest.IsAdjacentEdgesEmpty(IUndirectedGraph<String,Edge<String>>)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void IsAdjacentEdgesEmpty_IUndirectedGraph2_70429_213510_0_01()
        {
            this.IsAdjacentEdgesEmpty(((QuickGraph.IUndirectedGraph<string, QuickGraph.Edge<string>>)(null)));
        }
    }
}
