using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph
{
    
    
    public partial class VertexListGraphTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        [QuickGraph.Unit.TestAttribute()]
        [PexGeneratedBy(typeof(QuickGraph.VertexListGraphTest), "VertexListGraphTest.Iteration(IVertexListGraph<String,Edge<String>>)")]
        [GeneratedCode("Pex", "1.1.20430.1")]
        public void Iteration_IVertexListGraph2_70501_175755_1_01()
        {
            QuickGraph.AdjacencyGraph<string, QuickGraph.Edge<string>> ag0 = new QuickGraph.AdjacencyGraph<string, QuickGraph.Edge<string>>(false);
            this.Iteration(((QuickGraph.IVertexListGraph<string, QuickGraph.Edge<string>>)(ag0)));
        }
    }
}
