// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("QuickGraph.Data")]
[assembly: AssemblyProductAttribute("YC.QuickGraph")]
[assembly: AssemblyDescriptionAttribute("Graph datastructures and algorithms for .NET.")]
[assembly: AssemblyVersionAttribute("3.7.5")]
[assembly: AssemblyFileVersionAttribute("3.7.5")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "QuickGraph.Data";
        internal const System.String AssemblyProduct = "YC.QuickGraph";
        internal const System.String AssemblyDescription = "Graph datastructures and algorithms for .NET.";
        internal const System.String AssemblyVersion = "3.7.5";
        internal const System.String AssemblyFileVersion = "3.7.5";
    }
}
