using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Algorithms.ShortestPath
{
    
    
    public partial class DagShortestPathAlgorithmTest
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="System.ArgumentNullException">
        ///  Value cannot be null.
        ///Parameter name: g
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(System.ArgumentNullException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.ShortestPath.DagShortestPathAlgorithmTest), "DagShortestPathAlgorithmTest.Compute(IVertexListGraph<String,Edge<String>>)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void Compute_IVertexListGraph2_70429_213524_0_01()
        {
            this.Compute(((QuickGraph.IVertexListGraph<string, QuickGraph.Edge<string>>)(null)));
        }
    }
}
