using System.CodeDom.Compiler;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.CodeDom;
using QuickGraph.Unit;

namespace QuickGraph.Algorithms.ShortestPath
{
    
    
    public partial class DijkstraShortestPathAlgorithmTest2
    {
        
        /// <summary>
        ///  Test generated by Pex
        ///</summary>
        ///<remarks>
        ///  <para>
        ///    See http://codebox/pex/Wiki/View.aspx?title=Test+Failures for more information.
        ///  </para>
        ///</remarks>
        ///<exception cref="System.NullReferenceException">
        ///  Object reference not set to an instance of an object.
        ///</exception>
        [QuickGraph.Unit.TestAttribute()]
        [PexUnexpectedException(typeof(System.NullReferenceException))]
        [PexGeneratedBy(typeof(QuickGraph.Algorithms.ShortestPath.DijkstraShortestPathAlgorithmTest2), "DijkstraShortestPathAlgorithmTest2.Compute(IVertexAndEdgeListGraph<String,Edge<St" +
            "ring>>)")]
        [GeneratedCode("Pex", "1.1.20426.0")]
        public void Compute_IVertexAndEdgeListGraph2_70429_213421_0_01()
        {
            this.Compute(((QuickGraph.IVertexAndEdgeListGraph<string, QuickGraph.Edge<string>>)(null)));
        }
    }
}
